version: '3'
services:
    frontend:
        environment:
            - FONT_AWESOME_KEY
        ports:
            - 8081:3000
        image: ${IMAGE_NAME}:latest
        restart: always
        networks:
            - default
        deploy:
            replicas: 4
            
networks:
  app:
    driver: overlay
