version: '3'
services:
    frontend:
        image: ${IMAGE_NAME}:latest
        networks:
            - nginx-proxy-overlay
        deploy:
            replicas: 1
            labels:
                xyz.tangerie.reverse_proxy.path: "/"
                xyz.tangerie.reverse_proxy.port: "3000"
            
networks:
    nginx-proxy-overlay:
        external: true
        driver: overlay

