version: '3'

services:
    database:
        image: redislabs/redismod
        volumes:
            - redis-data:/data
            - redis-conf:/usr/local/etc/redis/redis.conf
        expose:
            - "6379"
        networks:
            - default
        

    api:
        ports:
            - 8080:8080
        depends_on:
            - database
        build: ./api
        environment:
            - REDIS_URL=redis://database:6379
        networks:
            - default
            - authenticationservice_default

    frontend:
        ports:
            - 8081:3000
        depends_on:
            - api
        build: 
            context: ./web
        networks:
            - default

volumes:
    redis-data:
    redis-conf:

networks:
    default:
        driver: bridge
    authenticationservice_default:
        external: true