version: '3'

services:
    frontend:
        ports:
            - 8081:3000
        image: docker.tangerie.xyz/portfolio-web:latest
        restart: always
        networks:
            - default
        deploy:
            replicas: 4
            
networks:
  app:
    driver: overlay
