version: '3'
services:
    frontend:
        ports:
            - 8081:3000
        image: ${IMAGE_NAME}:latest
        networks:
            - default
            - nginx-proxy-overlay
        deploy:
            replicas: 1
            labels:
                xyz.tangerie.reverse_proxy: "/"

            
networks:
    nginx-proxy-overlay:
        external: true
        driver: overlay
