version: '3'

services:
    api:
        ports:
            - 8080:8080
        build: ./api

    frontend:
        ports:
            - 8081:3000
        depends_on:
            - api
        build: 
            context: ./web