name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: [self-hosted, media]

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

    - name: Build the Docker image
      run: docker build --file Dockerfile --tag tangerie/portfolio:${{ steps.date.outputs.date }} .

    - name: Run the Docker image
      run: docker run --network=host -d --name portfolio --restart unless-stopped tangerie/portfolio:${{ steps.date.outputs.date }}