name: Docker Image CI

env:
  IMAGE_NAME: docker.tangerie.xyz/${{ github.event.repository.name }}
  ARCH_LIST: linux/arm64/v8,linux/amd64
  CURRENT_TAG: ${{ github.sha }}
  FONT_AWESOME_KEY: ${{ secrets.FONT_AWESOME_KEY }}

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, media]
    name: Build docker image to private registry
    steps:
      - name: Pull repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: docker.tangerie.xyz
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Print data
        run: echo Building to ${{env.IMAGE_NAME}} ${{env.CURRENT_TAG}} ${{env.FONT_AWESOME_KEY}}

      - name: Build and push web image
        run: >
          docker buildx build 
          --push
          --platform ${{env.ARCH_LIST}}
          -t ${{env.IMAGE_NAME}}:${{env.CURRENT_TAG}}
          -t ${{env.IMAGE_NAME}}:latest
          web

  deploy:
    name: Deploys docker image to swarm
    runs-on: [self-hosted, media]
    needs: build
    steps:
      - name: Pull repo
        uses: actions/checkout@v3

      - name: Run image
        run:  docker stack deploy -c docker-compose.yml ${{ github.event.repository.name }}